---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Anubhuti Talwar"
date: "09-22-2023"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:

```{r load-pkg-data}
#| message: false
library(Lahman)

```

## Exercises

### Exercise 1

```{r glimpse-data}
dplyr::glimpse(Teams)  # describes Teams dataset in R #
```

The `Teams` dataset has 3015 observations and 48 variables.

### Exercise 2

```{r}

library(dplyr) # Install dplyr package #

mets <- Teams %>%
  dplyr::filter(teamID == "NYN") # Filter Teams data for New York based on TeamID #

my_mets <- mets %>%
  dplyr::filter(yearID >= 2004 & yearID <= 2012) # Filter Teams data for New York based on year #

 my_mets %>% # Select columns - Year, W and L Team's performance  #
  dplyr::select(yearID , G,W,L) 

```

### Exercise 3

```{r}

mets_ben <- Teams |>
  dplyr::select(yearID, teamID, G, W, L, RA, RS = R) |>
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)
mets_ben

```

...

### Exercise 4

...

```{r}

mets_ben <- mets_ben %>%
  dplyr::mutate(WPct = 1 / (1 + (RA / RS) * 2))
mets_ben

mets_ben <- mets_ben |>
  dplyr::mutate(W_hat = WPct*G)
mets_ben

```

### Exercise 5

```{r}

library(dplyr)

mets_ben <- mets_ben %>%
  mutate(Performance = ifelse(W > W_hat, "Better", "Worse"))

summary_stats <- mets_ben %>%
  group_by(Performance) %>%
  summarize(count = n())

summary_stats
```

...

### Exercise 6

...

```{r}

best_seasons <- dplyr::arrange(mets_ben, desc(W)) 
best_seasons

```

### Exercise 7

```{r}

library(dplyr)
mets_ben <- mets_ben %>%
  mutate(Diff = W - W_hat) %>%
  arrange(desc(Diff))

View(mets_ben)

```

...

### Exercise 8

```{r}

mets_ben |>
  dplyr::summarize(
    num_years = n(), 
    total_W = sum(W), 
    total_L = sum(L), 
    total_WPct = mean(WPct), 
    sum_resid = sum(Diff)
  )
```

...

### Exercise 9

...

```{r}

# insufficient data so didn't attempt the question as specified by professor #
```

### Exercise 10

...

```{r}

library(dplyr)
mets_ben <- mets_ben %>% 
  dplyr::mutate(
    gm = ifelse(
      yearID <= 2004, "Jim Duquette",
      ifelse(
        yearID >= 2005 & yearID <= 2010, "Omar Minaya",
        ifelse(
          yearID >= 2011 & yearID <= 2012, "Sandy Alderson",
          NA
        )
      )
    )
  )
mets_ben
```

### Exercise 11

...

```{r}
library(dplyr)

manager_summary_stats <- mets_ben %>%   
group_by(gm) %>%   
summarize(num_years = n(),total_W = sum(W), total_L = sum(L),     total_WPct = mean(WPct),sum_resid = mean(Diff) )

manager_summary_stats

```
